### ISSUE TITLE
ClassNotFoundException: org.mockito.internal.MockitoInvocationHandler when using springockito-annotations with Mockito 1.10.19 (Are they compatible?)

### ISSUE THREAD

**Issue by christianbalzer** [springockito/springockito#7]
Hi!

I'm using `mockito-all 1.10.19` and `springockito` with `springockito-annotations`:

```
    <dependency>
        <groupId>org.kubek2k</groupId>
        <artifactId>springockito</artifactId>
        <version>1.0.9</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.kubek2k</groupId>
        <artifactId>springockito-annotations</artifactId>
        <version>1.0.9</version>
        <scope>test</scope>
    </dependency>
```

I have set up my test as described on http://www.springockito.org/ (I think):

```
@RunWith(SpringJUnit4ClassRunner.class)
@WebAppConfiguration
@ContextConfiguration(loader = SpringockitoContextLoader.class,
    locations = "classpath:test-applicationContext-mocked-controller.xml")
@ComponentScan(basePackageClasses = {MyController.class})
public class MyControllerMockedIntegrationTest extends AbstractJUnit4SpringContextTests {

    private MockMvc mockMvc;

    @Autowired
    private WebApplicationContext webApplicationContext;

    @Autowired
    @ReplaceWithMock
    private MyAdapter commissioningAdapter;
```

The test is supposed to test a controller using `MockMvc`. All classes that get injected into the controller are supposed to be replaced by mocks. (It's only `MyAdapterImpl`, actually.) When I don't use the annotations project (and set everything up in the XML file) it works fine.

But when I try to run the test with annotations instead, I get the following errors:
```
java.lang.IllegalStateException: Failed to load ApplicationContext

	at org.springframework.test.context.CacheAwareContextLoaderDelegate.loadContext(CacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.DefaultTestContext.getApplicationContext(DefaultTestContext.java:101)
	at ...
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping#0': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: org/mockito/internal/MockitoInvocationHandler
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1553)
	...
Caused by: java.lang.NoClassDefFoundError: org/mockito/internal/MockitoInvocationHandler
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
       ...
Caused by: java.lang.ClassNotFoundException: org.mockito.internal.MockitoInvocationHandler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	...
```

The following is essentially the content of my Spring config xml file (the component-scan directive probably being redundant); when I added `springockito-annotations`, I removed the line with the mock...

```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:mvc="http://www.springframework.org/schema/mvc" xmlns:mockito="http://www.mockito.org/spring/mockito"
       xsi:schemaLocation="
        http://www.springframework.org/schema/mvc http://www.springframework.org/schema/mvc/spring-mvc.xsd
        http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
        http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context.xsd
        http://www.mockito.org/spring/mockito http://www.mockito.org/spring/mockito.xsd
">

  <context:annotation-config/>
  <mvc:annotation-driven/>
  <context:component-scan base-package="com.example.foo" />

  <!-- This line removed when using springockito-annotations -->
  <mockito:mock id="myAdapter" class="com.example.MyAdapter" />

  <bean id="validator" class="org.springframework.validation.beanvalidation.MethodValidationPostProcessor"/>
</beans>
```

First of all, **is my usage right?** I just want a mock of `MyAdapter` to be injected into `MyController`. I do not use `MyAdapter` in my test at all (i.e. I don't set up any behaviour or run any asserts/verifies against it).

Secondly, **what version of Mockito is `springockito-annotations` compatible with?** (Clearly, it's not the one I'm using at the moment...)

**Comment by christianbalzer** [comment]
Just found this on [SO](http://stackoverflow.com/a/12159042/2018047):

> MockitoInvocationHandler was part of the Mockito's internals (as the package name suggests) up to Mockito 1.9.0.

It doesn't answer the question completely, save to say it must have been some version before Mockito 1.9.1 that [springockito-annotations](url) last worked with. In other words: a long time ago (current Mockito is [2.7.22](http://site.mockito.org/))...

Is anyone actually maintaining `springockito`, or is it just being hosted here?
